#!/usr/bin/env bash
# This script displays the listening ports of processes, their pids, program names, and state.

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tuln | awk '
  NR > 2 {
    if ($6 == "LISTEN") {
      if ($1 ~ /^tcp/) cmd = "ss -tuln"
      else if ($1 ~ /^udp/) cmd = "ss -uln"
      cmd = cmd " | grep -w " $4
      cmd | getline pid_prog
      close(cmd)
      split(pid_prog, a, ", ")
      sub(/\s*$/, "", a[2])
      printf("%-4s %-7s %-7s %-23s %-23s %-13s %s\n", $1, $2, $3, $4, $5, $6, a[2])
    }
  }'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
netstat -x | awk '
  NR > 1 {
    if ($1 ~ /^Active/ || $3 == "LISTENING") next
    if ($1 ~ /^Proto/) {
      sub(/ /, "", $2)
      next
    }
    cmd = "ss -x | grep -w " $6
    cmd | getline pid_prog
    close(cmd)
    split(pid_prog, a, ", ")
    sub(/\s*$/, "", a[2])
    printf("%-5s %-7s %-12s %-10s %-13s %-8s %s %s\n", $1, $2, $3, $4, $5, $6, a[1], $7)
  }'

