#!/usr/bin/env bash
# This script pings an IP address passed as an argument

# Check if an IP address is provided as an argument
if [ $# -ne 1 ]; then
  echo "Usage: $(basename "$0") {IP_ADDRESS}"
  exit 1
fi

# Get the IP address from the command line argument
ip_address="$1"

# Ping the IP address 5 times and display the results
ping -c 5 "$ip_address"
