#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid
# Display "To infinity and beyond" indefinitely
# Display " I hate the kill command" on receiving a SIGTERM signal
# Display "Y U no love me?!" on receiving a SIGINT signal
# Deletes the file "/var/run/myscript.pid" on receiving a SIGTERM or SIGQUIT signal.

echo $$ > "/var/run/myscript.pid"

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true; do
	echo "To infinity and beyond"
done
