#!/usr/bin/env bash
# Terminates a process without using kill or killall

# Start the 4-to_infinity_and_beyond script
./7-highlander

# Wait for the process to run for a while (you can adjust the duration as needed)
sleep 4

# Use pkill to send a SIGTERM signal to the process by its name
pkill -f "7-highlander"
echo "Terminated"
