#!/usr/bin/env bash
# Prints a statement on receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop with a sleep of 2 seconds
while true; do
    echo "To infinity and beyond"
    sleep 2
done
