#!/usr/bin/env bash
#Simulates a daemon/process outside of a terminal

# Writes "I am alive!" indefinitely to a file "/tmp/my_process
# Sleeps for 2 seconds after each iteration

while true; do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
