#!/usr/bin/env bash
# Prints from 1 to 100 with multiples of 3 printed as 'Fizz' and multiples of 5 printed as 'Buzz' while multiples of 3 and 5 are printed as 'FizzBuzz'.

for ((i = 1; i <= 100; i++)); do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo $i
    fi
done
