#!/usr/bin/env bash
# Prints "Best School" 9 out of ten times using while loop.

count=0

while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
