#!/usr/bin/env bash
# Prints "Best School" except that it prints "bad luck" in place 4and "Best School" in place 8.

count=1

while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
