#!/usr/bin/env bash
# Prints 1 to 20 using case statement.

count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo -e "$count\n7bad luck from China"
            ;;
        9)
            echo -e "$count\nbad luck from Japan"
            ;;
        17)
            echo -e "$count\nbad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    count=$((count + 1))
done
