#!/usr/bin/env bash
# Prints the time for 12 hours 59 minutes

hour=0

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    for ((minute = 1; minute <= 59; minute++)); do
        echo $minute
    done
    hour=$((hour + 1))
done
