#!/usr/bin/env bash
# Prints the time for 12 hours 59 minutes

hour=0

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    minute=0
    while [ $minute -le 59 ]; do
        echo $minute
	minute=$((minute + 1))
    done
    hour=$((hour + 1))
done
